[package]
name = "template"
version = "0.1.0"
edition = "2021"
license = "LGPLv3"
keywords = ["builder", "template", "struct-literal", "declarative", "DSL"]
categories = ["rust-patterns"]

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prelude = { path = "./prelude" }